---
title: "Scenario Modeling Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
params:
  pred.choose: 0
  aban.choose: 0
  mort.choose: 0
  fledge.choose: 0
  scen.include: 0
  lambda.export: NA
  scen.traj.probs: NA
  thresh.include: 0
  thresh.pred.include: 0
  thresholds: NA
  pred.thresholds: NA
  N0: 0
---

#Population Model
#### Parameters Chosen:
```{r error=T, echo=F} 
if(params$scen.include == 1){ #repeated three times in order to put display them on different lines
cat(paste("Predation Risk without Exclosures:", params$pred.choose, "%"))
}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Abandonment Risk Exclosures:", params$aban.choose, "%"))}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Mortality Risk with Abandonment:", params$mort.choose, "%"))}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Chick Survival (Hatch to Fledge):", params$fledge.choose, "%"))}
```



#### Predicted Population Growth Rates:

```{r error=T, echo=F}
library(knitr)
library(ggplot2)

if(params$scen.include == 1){
  
  g <- ggplot(params$lambda.export, aes(x=Exclosures, y=Growth)) +
    geom_violin(fill="grey") + 
    stat_summary(fun.y=mean, geom="point", shape=18, size=4) +
    theme(axis.text=element_text(size=12),
          axis.title=element_text(size=14, face="bold")) +
    geom_hline(yintercept = 1)
  
  print(g)

    
    kable(params$scen.traj.probs)
}

```

#Abandonment Tolerance
##If you plan to put up exclosures:
```{r error=T, echo=F}

if(params$thresh.include == 1){
  cat(paste("Starting # of pairs: ", params$N0))
  n.vals <- 200
  par(mar=c(5,5,4,2)+0.1)
    plot(x=NULL, y=NULL, xlab="Number of Exclosure-related Abandonments",
         ylab="Probability of Population Decline", ylim=c(0,1), xlim=c(0, max(params$thresholds$aban.ex.means)), 
         xaxt = "n")
    axis(1, at=seq(0,max(params$thresholds$aban.ex.means),by=1))
    prob.curv <- smooth.spline(params$thresholds$aban.ex.means, params$thresholds$prob.decline)
    lines(params$thresholds$prob.curv, lwd=2)
    if (length(params$thresholds$prob.curv$y)>=n.vals) {y.coord <- params$thresholds$prob.curv$y[1:200]} else 
    {y.coord <- c(params$thresholds$prob.curv$y[1:(n.vals-length(params$thresholds$prob.curv$y))], params$thresholds$prob.curv)}
    polygon(c(params$thresholds$aban.ex.means[1], params$thresholds$aban.ex.means, params$thresholds$aban.ex.means[n.vals]), 
            c(0,y.coord,0), density=10, angle=45)
    abline(h=params$thresholds$prob.decline.ref, lty=2, lwd=2)
    par(xpd=T)
    legend("topright", c("Exclosed", "Unexclosed Reference"), xpd=T, lty=c(1,2), lwd=c(2,2), adj=c(0,NA)) 
    
    cat(paste("Reassess or pull exclosures after ", params$thresholds$aban.tolerance, "observed nest abandonments"))
}
```

#Predation Tolerance
##If you plan to start without exclosures:
```{r error=T, echo=F}

  if(params$thresh.pred.include == 1){
    cat(paste("Starting # of pairs: ", params$N0))
    n.vals <- 200
    par(mar=c(5,5,4,2)+0.1)
    plot(x=NULL, y=NULL, xlab="Number of Nest Predations",
         ylab="Probability of Population Decline", ylim=c(0,1), xlim=c(0, max(params$pred.thresholds$preds.un.means)), 
         xaxt = "n")
    axis(1, at=seq(0,max(params$pred.thresholds$preds.un.means),by=1))
    prob.curv <- smooth.spline(params$pred.thresholds$preds.un.means, params$pred.thresholds$prob.decline)
    lines(params$pred.thresholds$prob.curv, lwd=2)
    if (length(params$pred.thresholds$prob.curv$y)>=n.vals) {y.coord <- params$pred.thresholds$prob.curv$y[1:200]} else 
    {y.coord <- c(params$pred.thresholds$prob.curv$y[1:(n.vals-length(params$pred.thresholds$prob.curv$y))], params$pred.thresholds$prob.curv)}
    polygon(c(params$pred.thresholds$preds.un.means[1], params$pred.thresholds$preds.un.means, params$pred.thresholds$preds.un.means[n.vals]), 
            c(0,y.coord,0), density=10, angle=45)
    abline(h=params$pred.thresholds$prob.decline.ref, lty=2, lwd=2)
    par(xpd=T)
    legend("topright", c("Exclosed", "Unexclosed Reference"), xpd=T, lty=c(1,2), lwd=c(2,2), adj=c(0,NA)) 
    
    cat(paste("Reassess or put up exclosures after ", params$pred.thresholds$pred.tolerance, "nest predations"))
  }
```
