---
title: "Scenario Modeling Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  pred.choose: 0
  aban.choose: 0
  mort.choose: 0
  fledge.choose: 0
  scen.include: 0
  scenario: NA
  scen.traj.probs: NA
  thresh.include: 0
  thresholds: NA
  N0: 0
---

#Population Model
#### Parameters Chosen:
```{r error=T, echo=F} 
if(params$scen.include == 1){ #repeated three times in order to put display them on different lines
cat(paste("Predation Risk without Exclosures:", params$pred.choose, "%"))
}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Abandonment Risk Exclosures:", params$aban.choose, "%"))}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Mortality Risk with Abandonment:", params$mort.choose, "%"))}
```
```{r echo = F}
if(params$scen.include == 1){
cat(paste("Chick Survival (Hatch to Fledge):", params$fledge.choose, "%"))}
```



#### Predicted Population Growth Rates:

```{r error=T, echo=F}
library(knitr)
if(params$scen.include == 1){
  plot(c(1,3), c(mean(params$scenario$lambda.ex), mean(params$scenario$lambda.un)), xlim=c(0,4), 
         ylim=c(
           min(quantile(params$scenario$lambda.ex,0.025),quantile(params$scenario$lambda.un, 0.025))-0.05, 
           max(quantile(params$scenario$lambda.ex,0.975),quantile(params$scenario$lambda.un, 0.975)+0.05)
         ),
         ylab="Population Growth Rate", xlab="", pch=c(15,0), lwd=2, cex=2, xaxt="n", cex.lab=1.5)
    axis(1, at=c(1,3), labels=c("Exclosures", "No Exclosures"), cex.axis=1.5)
    lines(c(1,1), c(quantile(params$scenario$lambda.ex,0.975), quantile(params$scenario$lambda.ex, 0.025)), lwd=2)
    lines(c(3,3), c(quantile(params$scenario$lambda.un,0.975), quantile(params$scenario$lambda.un, 0.025)), lwd=2)
    lines(c(1+0.05,1-0.05), c(quantile(params$scenario$lambda.ex,0.975), quantile(params$scenario$lambda.ex, 0.975)), lwd=2)
    lines(c(1+0.05,1-0.05), c(quantile(params$scenario$lambda.ex,0.025), quantile(params$scenario$lambda.ex, 0.025)), lwd=2)
    lines(c(3+0.05,3-0.05), c(quantile(params$scenario$lambda.un,0.975), quantile(params$scenario$lambda.un, 0.975)), lwd=2)
    lines(c(3+0.05,3-0.05), c(quantile(params$scenario$lambda.un,0.025), quantile(params$scenario$lambda.un, 0.025)), lwd=2)
    abline(h=1)
    
    kable(params$scen.traj.probs)
}

```

#Abandonment Tolerance
```{r error=T, echo=F}

if(params$thresh.include == 1){
  cat(paste("Starting # of pairs: ", params$N0))
  n.vals <- 200
  par(mar=c(5,5,4,2)+0.1)
    plot(x=NULL, y=NULL, xlab="Number of Exclosure-related Abandonments",
         ylab="Probability of Population Decline", ylim=c(0,1), xlim=c(0, max(params$thresholds$aban.ex.means)), 
         xaxt = "n")
    axis(1, at=seq(0,max(params$thresholds$aban.ex.means),by=1))
    prob.curv <- smooth.spline(params$thresholds$aban.ex.means, params$thresholds$prob.decline)
    lines(params$thresholds$prob.curv, lwd=2)
    if (length(params$thresholds$prob.curv$y)>=n.vals) {y.coord <- params$thresholds$prob.curv$y[1:200]} else 
    {y.coord <- c(params$thresholds$prob.curv$y[1:(n.vals-length(params$thresholds$prob.curv$y))], params$thresholds$prob.curv)}
    polygon(c(params$thresholds$aban.ex.means[1], params$thresholds$aban.ex.means, params$thresholds$aban.ex.means[n.vals]), 
            c(0,y.coord,0), density=10, angle=45)
    abline(h=params$thresholds$prob.decline.ref, lty=2, lwd=2)
    par(xpd=T)
    legend("topright", c("Exclosed", "Unexclosed Reference"), xpd=T, lty=c(1,2), lwd=c(2,2), adj=c(0,NA)) 
    
    cat(paste("Reassess or pull exclosures after ", params$thresholds$aban.tolerance, "observed nest abandonments"))
}
```
